/**
 * Autogenerated by ObjCToCppTranslator on 24/03/2016
 * @author Deep Shah
 * (c) 2015 Makkajai
 * This code is licensed under MIT license (see LICENSE.txt for details)
 */

#ifndef __BASELIGHTSOURCE_H__
#define __BASELIGHTSOURCE_H__
#include "cocos2d.h"

//
// Created by batman on 21/06/15.
//

#include "LightSource.h"


class BaseLightSource : public cocos2d::PointLight, public LightSource {

public:

    virtual void onExit() override;

    virtual ~BaseLightSource() override;

    virtual bool init() { return cocos2d::PointLight::init(); }

CC_SYNTHESIZE_RETAIN(cocos2d::__Array*, groups, Groups);

CC_SYNTHESIZE(cocos2d::Color3B, specularColor, SpecularColor);
CC_SYNTHESIZE(float, specularIntensity, SpecularIntensity);

CC_SYNTHESIZE(cocos2d::Color3B, ambientColor, AmbientColor);
CC_SYNTHESIZE(float, ambientIntensity, AmbientIntensity);

CC_SYNTHESIZE(float, depth, Depth);
CC_SYNTHESIZE(float, cutoffRadius, CutoffRadius);
CC_SYNTHESIZE(float, halfRadius, HalfRadius);
CC_SYNTHESIZE(float, brightness, Brightness);
CC_SYNTHESIZE(float, ambientBrightness, AmbientBrightness);

CREATE_FUNC(BaseLightSource);

public: 

bool initWithLightSourceDetail(LightSourceDetail * detail);
};

#endif // __BASELIGHTSOURCE_H__