/**
 * Autogenerated by ObjCToCppTranslator on 24/03/2016
 * @author Deep Shah
 * (c) 2015 Makkajai
 * This code is licensed under MIT license (see LICENSE.txt for details)
 */

#ifndef __LIGHTSOURCE_H__
#define __LIGHTSOURCE_H__
#include "cocos2d.h"

//
// Created by batman on 21/06/15.
//


class LightSourceDetail;

class LightSource {

public:

virtual bool initWithLightSourceDetail(LightSourceDetail * detail) = 0;



};

#endif // __LIGHTSOURCE_H__